---
name: RocketAPIWorkFlow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Deploy:
    runs-on:
      - ubuntu-latest
    steps:
      - name: setup demo
        run: |
          mkdir test
          touch test/oof.txt
          touch test/.dot.txt
      - name: checkout
        uses: actions/checkout@v1
      - name: Copy folder content recursively to remote
        uses: ./.github/workflows/dotnet.yml/
        with:
          local: test
          remote: scp/directory
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
