---
name: RocketAPIWorkFlow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Deploy:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code
      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: "C:\\Users\\UTIS LAPTOP 252\\Downloads"
          remote: "\\USNYMEQARKTMX2\\TestFolder"
          host: "USNYMEQARKTMX2"
          username: "VMONI1"
          password: "Network@3"
          
