---
name: RocketAPIWorkFlow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Deploy:
    runs-on:
      - ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 10.80.77.63
        username: USHSI\VITHEYA.MONIKHA
        password: Passwordforhs@9595
        port: 22
        script: whoami
