---
name: RocketAPIWorkFlow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Deploy:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code
      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./.github
          remote: \\USNYMEQARKTMX2\\TestAgain
          host: USNYMEQARKTMX2
          username: USHSI\VITHEYA.MONIKHA
          password: Passwordforhs@9595
          privateKey: ${{ secrets.PRIVATE_KEY}}
