---
name: RocketAPIWorkFlow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Deploy:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Perform a Pester test from the command-line
        shell: pwsh
        run: Test-NetConnection -ComputerName USNYMEQARKTMX2 -Port 22
