---
name: RocketAPIWorkFlow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Deploy:
    runs-on:
      - ubuntu-latest
    steps:
    - name: Action SSH
      uses: tiyee/action-ssh@release
      with:
          host: USNYMEQARKTMX2
          port: 22
          username: USHSI\VITHEYA.MONIKHA
          privateKey: ${{ secrets.PRIVATE_KEY }} 
          command: 'ls -alh'
