name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
   ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore RestFulAPI_Legasuite/RestFulAPI_Legasuite.sln
 
    - name: Build and Publish Web App
      run: msbuild RestFulAPI_Legasuite/Publish /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: published_webapp
        path: D:\a\Git-action\Git-action\RestFulAPI_Legasuite/Publish
